### ISSUE TITLE
tkn logs segfaults if run not started

### ISSUE THREAD

**Issue by faust64** [tektoncd/pipeline#1584]
# Expected Behavior

Some info/error/warning, notifying me the job has not started yet

# Actual Behavior

```
$ tkn pipelinerun list
NAME                              STARTED        DURATION     STATUS      
....
nextcloud-wsweet-master-1         ---            ---          ---         
...
$ tkn pipelinerun logs nextcloud-wsweet-master-1
panic: runtime error: index out of range [0] with length 0

goroutine 34 [running]:
github.com/tektoncd/cli/pkg/cmd/pipelinerun.(*LogReader).readAvailableLogs.func1(0xc000772000, 0xc000772060, 0x23cb680, 0x0, 0x0, 0xc000200720, 0xc0000e0a00)
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/log_reader.go:137 +0x3a5
created by github.com/tektoncd/cli/pkg/cmd/pipelinerun.(*LogReader).readAvailableLogs
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/log_reader.go:126 +0x2e1
```

# Steps to Reproduce the Problem

1. pile up several pipelineruns
2. use tkn pipelinerun logs against a job that did not start

**Comment by sbwsg** [comment]
This sounds like it belongs in the tkn/CLI repo: https://github.com/tektoncd/cli/issues

**Comment by faust64** [comment]
Sure.

https://github.com/tektoncd/cli/issues/470
