### ISSUE TITLE
Tekton pipeline controller during `updatePipelineRunStatusFromTaskRuns`

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#3000]
# Expected Behavior
The controller does not crash

# Actual Behavior
While authoring a pipeline with conditions, I managed to crash the controller.

```
$ k get pods -n tekton-pipelines
NAME                                           READY   STATUS             RESTARTS   AGE
tekton-pipelines-controller-68fbf95d4b-wqh76   0/1     CrashLoopBackOff   53         2d2h
```

```
$ k logs -n tekton-pipelines tekton-pipelines-controller-68fbf95d4b-wqh76
(...)
panic: assignment to entry in nil map

goroutine 266 [running]:
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.updatePipelineRunStatusFromTaskRuns(0xc00119a8e0, 0xc000c9cf80, 0x20, 0x0, 0xc00039f6c0, 0x1, 0x1, 0x0, 0xc001228960, 0x0, ...)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:922 +0xb07
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).updatePipelineRunStatusFromInformer(0xc000e82180, 0x2141920, 0xc0012154d0, 0xc0010c8b40, 0x8, 0xc000c9cf80)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:870 +0x2a8
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind(0xc000e82180, 0x2141920, 0xc0012154d0, 0xc0010c8b40, 0xc0010c8b40, 0x0)
	github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:196 +0x55f
github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun.(*reconcilerImpl).Reconcile(0xc00018d680, 0x2141920, 0xc001215470, 0xc00101eed0, 0x29, 0xc00119a8e0, 0x2141920)
	github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun/reconciler.go:237 +0x1299
github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc000b4cd70, 0x0)
	github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:465 +0x785
github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext.func3(0xc000526870, 0xc000b4cd70)
	github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:403 +0x53
created by github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext
	github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:401 +0x1f5
```

It looks like the issue is in:
https://github.com/tektoncd/pipeline/blob/7453c403e28b877208aaf466e159354563e01641/pkg/reconciler/pipelinerun/pipelinerun.go#L922

If `prStatus.TaskRuns` is not initialised.

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.11+IKS", GitCommit:"c33b093e937d1f9eee340f9bddfa14e1e54ad1a4", GitTreeState:"clean", BuildDate:"2020-06-17T21:37:54Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

I installed from master with `ko` so it's version v0.14.2+

```
Client version: 0.10.0
Pipeline version: devel
Triggers version: v0.6.1
```

**Comment by bobcatfish** [comment]
oooo good catch

**Comment by bobcatfish** [comment]
![image](https://user-images.githubusercontent.com/432502/88417861-b2726100-cdb0-11ea-9dac-fd30294d8de2.png)
