### ISSUE TITLE
index out of range [1] with length 1 in validateMatrixedPipelineTaskConsumed

### ISSUE THREAD

**Issue by peterh-of** [tektoncd/pipeline#7541]
# Expected Behavior
The pipeline is started without any issue

# Actual Behavior
I get an error message in tekton-pipelines-webhook:

http: panic serving 10.130.0.2:39504: runtime error: index out of range [1] with length 1

And an error message in the pipelines-as-code-controller:
{"level":"error","ts":"2024-01-02T10:55:34.732Z","logger":"pipelinesascode","caller":"events/emit.go:46","msg":"There was an error starting the PipelineRun csharp-build-api-, creating pipelinerun csharp-build-api- in namespace pipelines-dotnet has failed.\n\nTekton Controller has reported this error: ```Internal error occurred: failed calling webhook \"validation.webhook.pipeline.tekton.dev\": failed to call webhook: Post \"https://tekton-pipelines-webhook.openshift-pipelines.svc:443/resource-validation?timeout=10s\": EOF``` ","provider":"github","event-id":"6e015da0-a95d-11ee-9362-f3ffd286b82d","event-sha":"e149ac8c764b86c374255f98931bc662ce52fb78","event-type":"pull_request","namespace":"pipelines-dotnet","stacktrace":"github.com/openshift-pipelines/pipelines-as-code/pkg/events.(*EventEmitter).EmitMessage\n\t/go/src/github.com/openshift-pipelines/pipelines-as-code/pkg/events/emit.go:46\ngithub.com/openshift-pipelines/pipelines-as-code/pkg/pipelineascode.(*PacRun).Run.func1\n\t/go/src/github.com/openshift-pipelines/pipelines-as-code/pkg/pipelineascode/pipelineascode.go:92"}

# Steps to Reproduce the Problem
1.
Create a pipeline with a task with the following parameter:
     - params:
        - name: GIT_SCRIPT
          value: |
            #!/bin/bash 

            # Change directory to the root of the Git repository
            cd $(workspaces.source.path)/$(params.APP_GIT_SUBDIRECTORY)

            # Change the ownership of the files in the repository
            chown -R $(whoami) .

            # Fetch all tags from the remote repository
            git fetch --tags

            # Get the new version from the result of the extract-version task
            NEW_VERSION=$(tasks.extract-tag-and-version.results.VERSION)

            # checkout the target branch
            git checkout -b $(params.BRANCH)

            # Check if the tag already exists
            if git rev-parse "$NEW_VERSION" >/dev/null 2>&1; then
              # Get the commit hash associated with the tag
              TAG_COMMIT=$(git rev-list -n 1 $NEW_VERSION)

              # Get the hash of the current commit
              CURRENT_COMMIT=$(git rev-parse HEAD)

              # If the tag is associated with a different commit, exit with an error
              if [ "$TAG_COMMIT" != "$CURRENT_COMMIT" ]; then
                echo "Error: Tag $NEW_VERSION already exists on a different commit"
                exit 1
              fi
            else
              # Create a new tag with the new version
              git tag $NEW_VERSION
              # Push the new tag to the remote repository
              git push origin $NEW_VERSION
            fi

2.
Now make a pipelinerun in the .tekton folder and run the pipeline
3.
The error occurs. I think it is caused by the function findAndValidateResultRefsForMatrix. It retrieves all expressions for the parameter with GetVarSubstitutionExpressions. It then checks if any of them is a results expression. This is true because of $(tasks.extract-tag-and-version.results.VERSION).
It then calls validateMatrixedPipelineTaskConsumed which loops over all expressions. I think it sees $(git rev-parse HEAD) as an expression which causes the index out of range error.

# Additional Info
Error message in tekton-pipelines-webhook:
{"severity":"error","timestamp":"2024-01-02T10:51:04.571Z","logger":"tekton-pipelines-webhook","caller":"webhook/webhook.go:237","message":"http: panic serving 10.130.0.2:39504: runtime error: index out of range [1] with length 1\ngoroutine 3643940 [running]:\nnet/http.(*conn).serve.func1()\n\t/usr/lib/golang/src/net/http/server.go:1854 +0xbf\npanic({0x1f08660, 0xc005803440})\n\t/usr/lib/golang/src/runtime/panic.go:890 +0x263\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.validateMatrixedPipelineTaskConsumed({0xc0054b7040?, 0x5, 0x204d9de?}, 0x6?)\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:813 +0x3b8\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.findAndValidateResultRefsForMatrix({0xc0048e0000?, 0xb, 0x0?}, 0xea0094bb00000000?)\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:795 +0x292\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.validateTaskResultsFromMatrixedPipelineTasksConsumed({0xc0048e0000, 0xb, 0xd})\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:831 +0x189\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.validateMatrix({0x2349aa8, 0xc0047f2f60}, {0xc0048e0000?, 0xb, 0xd})\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:783 +0x137\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.(*PipelineSpec).Validate(0xc0044ad220, {0x2349aa8, 0xc0047f2f60})\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:88 +0x69b\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.(*PipelineRunSpec).Validate(0xc00475b0c8, {0x2349aa8, 0xc0047f2f60})\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipelinerun_validation.go:68 +0x307\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.(*PipelineRun).Validate(0xc00475afc0, {0x2349aa8, 0xc0047f2f30})\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipelinerun_validation.go:48 +0x19f\nknative.dev/pkg/webhook/resourcesemantics/validation.validate({0x2349aa8, 0xc0047f2f30}, {0x2349fe8, 0xc00475afc0}, 0xc00505d380)\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go:182 +0x127\nknative.dev/pkg/webhook/resourcesemantics/validation.(*reconciler).Admit(0xc0002caf00, {0x2349aa8?, 0xc0047f25a0?}, 0xc00505d380)\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go:79 +0x1c5\nknative.dev/pkg/webhook.admissionHandler.func1({0x23488f0?, 0xc004461c00}, 0xc004741100)\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/admission.go:123 +0x7fb\nnet/http.HandlerFunc.ServeHTTP(0xc0036c9a38?, {0x23488f0?, 0xc004461c00?}, 0x6b0425?)\n\t/usr/lib/golang/src/net/http/server.go:2122 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0xc0047f2390?, {0x23488f0, 0xc004461c00}, 0xc004741100)\n\t/usr/lib/golang/src/net/http/server.go:2500 +0x149\nknative.dev/pkg/webhook.(*Webhook).ServeHTTP(0xc0002cacc0, {0x23488f0, 0xc004461c00}, 0xc004741100)\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/webhook.go:320 +0xb3\nknative.dev/pkg/network/handlers.(*Drainer).ServeHTTP(0xc000488230, {0x23488f0, 0xc004461c00}, 0xc004741100)\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/network/handlers/drain.go:113 +0x15e\nnet/http.serverHandler.ServeHTTP({0x23398d0?}, {0x23488f0, 0xc004461c00}, 0xc004741100)\n\t/usr/lib/golang/src/net/http/server.go:2936 +0x316\nnet/http.(*conn).serve(0xc005343710, {0x2349aa8, 0xc0008e07b0})\n\t/usr/lib/golang/src/net/http/server.go:1995 +0x612\ncreated by net/http.(*Server).Serve\n\t/usr/lib/golang/src/net/http/server.go:3089 +0x5ed\n","commit":"876b81e","stacktrace":"knative.dev/pkg/webhook.(*zapWrapper).Write\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/webhook.go:237\nlog.(*Logger).Output\n\t/usr/lib/golang/src/log/log.go:194\nlog.(*Logger).Printf\n\t/usr/lib/golang/src/log/log.go:204\nnet/http.(*Server).logf\n\t/usr/lib/golang/src/net/http/server.go:3215\nnet/http.(*conn).serve.func1\n\t/usr/lib/golang/src/net/http/server.go:1855\nruntime.gopanic\n\t/usr/lib/golang/src/runtime/panic.go:890\nruntime.goPanicIndex\n\t/usr/lib/golang/src/runtime/panic.go:113\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.validateMatrixedPipelineTaskConsumed\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:813\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.findAndValidateResultRefsForMatrix\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:795\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.validateTaskResultsFromMatrixedPipelineTasksConsumed\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:831\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.validateMatrix\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:783\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.(*PipelineSpec).Validate\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_validation.go:88\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.(*PipelineRunSpec).Validate\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipelinerun_validation.go:68\ngithub.com/tektoncd/pipeline/pkg/apis/pipeline/v1.(*PipelineRun).Validate\n\t/go/src/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipelinerun_validation.go:48\nknative.dev/pkg/webhook/resourcesemantics/validation.validate\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go:182\nknative.dev/pkg/webhook/resourcesemantics/validation.(*reconciler).Admit\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go:79\nknative.dev/pkg/webhook.admissionHandler.func1\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/admission.go:123\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/golang/src/net/http/server.go:2122\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/lib/golang/src/net/http/server.go:2500\nknative.dev/pkg/webhook.(*Webhook).ServeHTTP\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/webhook/webhook.go:320\nknative.dev/pkg/network/handlers.(*Drainer).ServeHTTP\n\t/go/src/github.com/tektoncd/pipeline/vendor/knative.dev/pkg/network/handlers/drain.go:113\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/golang/src/net/http/server.go:2936\nnet/http.(*conn).serve\n\t/usr/lib/golang/src/net/http/server.go:1995"}

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: 4.9.0-202206271415.p0.g728b452.assembly.stream-728b452
Kubernetes Version: v1.25.11+1485cc9
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.30.1
Chains version: v0.19.0
Pipeline version: v0.53.3
Triggers version: v0.25.3
Operator version: v0.69.1
```

**Comment by sambonbonne** [comment]
It seems I have the sme issue, `tkn version` returns the following:

```text
Client version: 0.34.0
Pipeline version: v0.58.0
Triggers version: v0.26.1
```

I run Tekton pipelines on an Oracle OCI cluster, on ARM64 nodes.

I have two pipelines:

* one containing a `matrix` setting, I triggered it one hour before I got the bug and it worked fine except they where in a `Failed` state (despite the fact that everything seemed to work and the logs where OK)
* another which does not contain any `matrix` section and for which the `PipelineRun` I just triggered is stuck in the `ResolvingTaskRef` state

I tried to delete the preceding `PipelineRuns` and restart the Tekton pipelines controller but it did not help.
